### ISSUE TITLE
Can somebody help me with the installation process?

### ISSUE THREAD

**Issue by ghost** [Technowlogy-Pushpender/KratosKnife#10]
I unzipped the 'panel' folder, and installed php to execute the php files. However, I need help with the steps in between.

Could someone make a video on how to install it, or write detailed steps for the installation please?

**Comment by N0tab** [comment]
You dont execute the files you're sure ur not a kid that is going to use it for threantning people on discord anyways its super complicated needs linux or python and you need xmpp

**Comment by kgnfth** [comment]
> You dont execute the files you're sure ur not a kid that is going to use it for threantning people on discord anyways its super complicated needs linux or python and you need xmpp

like u are going to use it as a legal shit ?
yea right

**Comment by drunkm3m3r** [comment]
> > You dont execute the files you're sure ur not a kid that is going to use it for threantning people on discord anyways its super complicated needs linux or python and you need xmpp
> 
> like u are going to use it as a legal shit ? yea right

his name's squidward why are you still wondering
