### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by pjeklo** [Technowlogy-Pushpender/KratosKnife#13]
←[93m
[*] Initiating AES Encryption Process ...
←[1;32m[+] Process Completed Successfully!
←[93m
[*] Compiling Source codes ...←[1;35m
The filename, directory name, or volume label syntax is incorrect.

[*] Deleting Junk Files ...
[+] Deleted Successfully !

**Comment by pjeklo** [comment]
I changed in Generator.py, pyinstaller path to exact path copied from my pc and it worked. But I still dont see device in panel...

**Comment by Sup0987** [comment]
help with this please? 

<img width="627" height="889" alt="Image" src="https://github.com/user-attachments/assets/2758dd0e-6314-42c5-95b1-e2b56177818e" />
<img width="1108" height="613" alt="Image" src="https://github.com/user-attachments/assets/84df7f2d-287a-4145-88cb-bb8d1d24e12b" />
